apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sc3f1yelv-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/sc3f1yelv-java-springboot-gitops